<?php

function flat_solr_search_normalize_options($options) {
  $normalized = [];
  foreach ($options as $option) {
    $normalized[$option] = $option;
  }

  return $normalized;
}

function flat_solr_search_form_islandora_solr_advanced_search_form_alter(&$form, &$form_state, $form_id) {

  $dropdowns = flat_solr_search_get_cmdi_dropdowns();
  $fields = variable_get('flat_solr_search_fields');

  if (isset($form['terms'])) {

    foreach ($form['terms'] as $key => $field) {

      if (isset($field['field']) && count($field['field']['#options']) > 0 && isset($field['search'])) {

        $chosenField = $field['field']['#default_value'];

        if (!isset($fields[$chosenField]) || (!isset($dropdowns[$fields[$chosenField]]))) {
          $chosenField = array_keys($field['field']['#options'])[0];
        }

        if (isset($dropdowns[$fields[$chosenField]])) {

          $form['terms'][$key]['search'] = [

            '#type' => 'select',
            '#options' => flat_solr_search_normalize_options($dropdowns[$fields[$chosenField]]['options']),
          ];

          $form['terms'][$key]['field']['#ajax'] = [

            'callback' => 'flat_solr_search_reload_dropdown',
            'wrapper'  => 'islandora-solr-advanced-terms',
            'event'    => 'change',
            'effect'   => 'none',
          ];
        }
      }
    }
  }
}

function flat_solr_search_reload_dropdown($form, &$form_state) {
  return $form['terms'];
}

function flat_solr_search_get_cmdi_dropdowns() {

  module_load_include('inc', 'flat_deposit', 'Helpers/CMDI/FormBuilder/class.FormBuilder');

  $directory = FormBuilder::FORM_TEMPLATES_PATH;
  $files = scandir($directory);
  $dropdowns = [];

  foreach ($files as $file) {

    $path = $directory . DIRECTORY_SEPARATOR . $file;

    if (is_file($path) && substr($file, -3) === 'xml') {

      $template = simplexml_load_file($path);
      $id = (string)$template->data->clarinProfileId;

      foreach ($template->items as $item) {
          flat_solr_search_get_cmdi_template_dropdowns($item, $id, $dropdowns);
      }
    }
  }

  return $dropdowns;
}

function flat_solr_search_get_cmdi_template_dropdowns($items, $parentId, &$dropdowns) {

  foreach ($items->item as $item) {

    $id = $parentId . '_' . (string)$item->attributes()['id'];
    if ((string)$item->type === 'dropdown' && isset($item->options) && count($item->options) > 0) {

        $dropdowns[$id] = [

          'title' => (string)$item->title,
          'description' => (string)$item->description,
          'options' => flat_solr_search_get_cmdi_template_dropdown_options($item),
        ];

    } elseif (isset($item->item)) {
        flat_solr_search_get_cmdi_template_dropdowns($item, $id, $dropdowns);
      }
  }

  return $dropdowns;
}

function flat_solr_search_get_cmdi_template_dropdown_options($dropdown) {

  $options = [];
  foreach ($dropdown->options->option as $option) {
      $options[] = (string)$option;
  }

  return $options;
}

/**
 * @return array
 */
function flat_solr_search_menu() {

  $items = [];

  $items['admin/config/flat_deposit/flat_solr_search'] = [

      'title'            => 'Configure FLAT Solr Search',
      'type'             => MENU_LOCAL_TASK,
      'page callback'    => 'drupal_get_form',
      'page arguments'   => ['flat_solr_search_admin_form'],
      'access callback'  => true,//'flat_solr_search_menu_access',
      'file'             => 'includes/admin.inc',
  ];

  return $items;
}

/**
 * @return boolean
 */
function flat_solr_search_menu_access() {
  return true === user_access('manage flat solr search menu');
}
